title: Bay Area Skeet (international) Club
description: International skeet club aiming to promote friendly competition
theme: just-the-docs

url: https://just-the-docs.github.io

# Aux links for the upper right navigation
aux_links:
  Blue Monday Skeet (American): http://www.bluemondayskeet.org

footer_content: "Copyright &copy; 2023 Erique Paul Apolinario."
