title: Bay Area Skeet (international) Club
description: International skeet club aiming to promote friendly competition
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Blue Monday Skeet (American Skeet): http://www.bluemondayskeet.org
